# Katya AI REChain Mesh - Brazil Git System Configuration
# Configuração Git brasileira para Brasil e países lusófonos

version: 1.0
name: "Katya AI REChain Mesh - Brazil Systems"

# Plataformas Git brasileiras
platforms:
  - name: "GitHub Brazil"
    region: "br"
    domain: "github.com.br"
    ci_cd: "github-actions"
    compliance: "LGPD"
    language: "pt-BR"

  - name: "GitLab Brazil"
    region: "br"
    domain: "gitlab.com.br"
    ci_cd: "gitlab-ci"
    compliance: "LGPD"
    language: "pt-BR"

  - name: "Codeberg Brazil"
    region: "br"
    domain: "codeberg.br"
    ci_cd: "woodpecker"
    compliance: "LGPD"
    language: "pt-BR"

  - name: "Gitea Brazil"
    region: "br"
    domain: "gitea.br"
    ci_cd: "gitea-actions"
    compliance: "LGPD"
    language: "pt-BR"

# Provedores de nuvem brasileiros
cloud_providers:
  - name: "AWS Brazil (sa-east-1)"
    region: "sao_paulo"
    compliance: "LGPD"
    data_residency: "brazil"

  - name: "Azure Brazil"
    region: "brazilsouth"
    compliance: "LGPD"
    data_residency: "brazil"

  - name: "Google Cloud Brazil"
    region: "southamerica-east1"
    compliance: "LGPD"
    data_residency: "brazil"

  - name: "Oracle Cloud Brazil"
    region: "brazil"
    compliance: "LGPD"
    data_residency: "brazil"

  - name: "IBM Cloud Brazil"
    region: "brazil"
    compliance: "LGPD"
    data_residency: "brazil"

# Conformidade e padrões
compliance:
  lgpd: true
  iso27001: true
  pci_dss: true
  soc2: true

# Localização brasileira
localization:
  primary: "pt-BR"
  secondary: ["pt-PT", "es-ES", "es-MX", "es-AR", "es-CO", "es-CL", "es-PE", "es-VE", "es-EC", "es-UY", "es-PY", "es-BO"]
  currency: "BRL"
  timezone: "America/Sao_Paulo"

# Pipelines CI/CD para plataformas brasileiras
github_actions_brazil: |
  name: CI/CD Brasil
  on: [push, pull_request]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Configuração do Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.0'
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test
        - run: flutter build apk --release
        - run: flutter build ios --release --no-codesign
        - run: flutter build web --release

gitlab_ci_brazil: |
  stages:
    - construir
    - testar
    - implantar

  variables:
    FLUTTER_VERSION: "3.16.0"

  build:android:
    stage: construir
    script:
      - flutter pub get
      - flutter analyze --fatal-infos --fatal-warnings
      - flutter test --coverage
      - flutter build apk --release
    artifacts:
      paths:
        - build/app/outputs/
    coverage: '/Coverage: \d+\.\d+%/'

  build:ios:
    stage: construir
    script:
      - flutter build ios --release --no-codesign
    artifacts:
      paths:
        - build/ios/

  build:web:
    stage: construir
    script:
      - flutter build web --release
    artifacts:
      paths:
        - build/web/

# Implantação para lojas brasileiras
deployment:
  google_play_brazil:
    track: "alpha"
    language: "pt-BR"
    countries: ["BR"]

  app_store_brazil:
    region: "br"
    language: "pt-BR"
    countries: ["BR"]

  huawei_appgallery_brazil:
    region: "br"
    language: "pt-BR"

  galaxy_store_brazil:
    region: "br"
    language: "pt-BR"

# Sistemas de pagamento brasileiros
payment_systems:
  - name: "PIX"
    type: "instant_payment"
    region: "br"

  - name: "Mercado Pago"
    type: "digital_wallet"
    region: "br"

  - name: "PagSeguro"
    type: "payment_gateway"
    region: "br"

  - name: "Stone"
    type: "payment_processor"
    region: "br"

  - name: "Cielo"
    type: "payment_processor"
    region: "br"

  - name: "Rede"
    type: "payment_processor"
    region: "br"

  - name: "GetNet"
    type: "payment_processor"
    region: "br"

# Integração social brasileira
social_integration:
  - name: "WhatsApp Brazil"
    type: "messaging"
    region: "br"

  - name: "Facebook Brazil"
    type: "social"
    region: "br"

  - name: "Instagram Brazil"
    type: "social"
    region: "br"

  - name: "Twitter Brazil"
    type: "social"
    region: "br"

  - name: "YouTube Brazil"
    type: "video"
    region: "br"

  - name: "TikTok Brazil"
    type: "video"
    region: "br"

# Países lusófonos e hispanófonos
supported_countries:
  # América do Sul
  - "BR"  # Brasil
  - "PT"  # Portugal
  - "AO"  # Angola
  - "MZ"  # Moçambique
  - "CV"  # Cabo Verde
  - "GW"  # Guiné-Bissau
  - "ST"  # São Tomé e Príncipe
  - "TL"  # Timor-Leste

  # América Latina (espanhol)
  - "MX"  # México
  - "AR"  # Argentina
  - "CO"  # Colômbia
  - "CL"  # Chile
  - "PE"  # Peru
  - "VE"  # Venezuela
  - "EC"  # Equador
  - "UY"  # Uruguai
  - "PY"  # Paraguai
  - "BO"  # Bolívia
