# Katya AI REChain Mesh - German Git System Configuration
# Deutsche Git-Plattformen und CI/CD für Deutschland, Österreich, Schweiz

version: 1.0
name: "Katya AI REChain Mesh - German Systems"

# Deutsche Git-Plattformen
platforms:
  - name: "GitHub Germany"
    region: "de"
    domain: "github.de"
    ci_cd: "github-actions"
    compliance: "DSGVO"
    language: "de"

  - name: "GitLab Germany"
    region: "de"
    domain: "gitlab.de"
    ci_cd: "gitlab-ci"
    compliance: "DSGVO"
    language: "de"

  - name: "Bitbucket Germany"
    region: "de"
    domain: "bitbucket.de"
    ci_cd: "bitbucket-pipelines"
    compliance: "DSGVO"
    language: "de"

  - name: "Codeberg Germany"
    region: "de"
    domain: "codeberg.de"
    ci_cd: "woodpecker"
    compliance: "DSGVO"
    language: "de"

  - name: "Gitea Germany"
    region: "de"
    domain: "gitea.de"
    ci_cd: "gitea-actions"
    compliance: "DSGVO"
    language: "de"

# Cloud-Anbieter Deutschland
cloud_providers:
  - name: "AWS Germany (eu-central-1)"
    region: "frankfurt"
    compliance: "C5"
    data_residency: "germany"

  - name: "Azure Germany"
    region: "germanywestcentral"
    compliance: "C5"
    data_residency: "germany"

  - name: "Google Cloud Germany"
    region: "europe-west3"
    compliance: "C5"
    data_residency: "germany"

# Compliance und Standards
compliance:
  dsgvo: true
  c5: true
  iso27001: true
  bsi: true

# Deutsche Lokalisierung
localization:
  primary: "de-DE"
  secondary: ["de-AT", "de-CH"]
  currency: "EUR"
  timezone: "Europe/Berlin"

# CI/CD Pipelines für deutsche Plattformen
github_actions_germany: |
  name: German CI/CD
  on: [push, pull_request]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.0'
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test
        - run: flutter build apk --release
        - run: flutter build ios --release --no-codesign
        - run: flutter build web --release

gitlab_ci_germany: |
  stages:
    - build
    - test
    - deploy

  variables:
    FLUTTER_VERSION: "3.16.0"

  build:android:
    stage: build
    script:
      - flutter pub get
      - flutter analyze
      - flutter test
      - flutter build apk --release
    artifacts:
      paths:
        - build/app/outputs/

  build:ios:
    stage: build
    script:
      - flutter build ios --release --no-codesign
    artifacts:
      paths:
        - build/ios/

  build:web:
    stage: build
    script:
      - flutter build web --release
    artifacts:
      paths:
        - build/web/

# Deployment für deutsche Stores
deployment:
  google_play_germany:
    track: "alpha"
    language: "de"

  app_store_germany:
    region: "de"
    language: "de"

  huawei_appgallery_germany:
    region: "de"
    language: "de"
