# GitVerse CI Configuration
# Modern CI/CD pipeline for GitVerse

version: "1.0"
name: "Katya AI REChain Mesh CI/CD"

environment:
  flutter: "3.16.0"
  java: "17"
  node: "18"
  go: "1.21"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter }}
          cache: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.java }}
          distribution: temurin

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node }}
          cache: npm

      - name: Install dependencies
        run: |
          flutter pub get
          npm install

  analyze:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter }}
          cache: true

      - name: Analyze code
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Run tests
        run: |
          flutter test --coverage
          flutter test integration_test

      - name: Upload coverage
        uses: codecov/codecov-action@v3

  build:
    runs-on: ${{ matrix.os }}
    needs: analyze
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        platform: [web, android, ios, linux, windows, macos]
        exclude:
          - os: ubuntu-latest
            platform: ios
          - os: windows-latest
            platform: ios
          - os: macos-latest
            platform: windows
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-latest
            target: windows
          - os: macos-latest
            target: macos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter }}
          cache: true

      - name: Build ${{ matrix.platform }}
        run: flutter build ${{ matrix.platform }} --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-build
          path: build/${{ matrix.platform }}/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Deploy to GitVerse Pages
        run: echo "Deploy web build to GitVerse Pages"

      - name: Deploy to stores
        run: echo "Deploy mobile and desktop builds to respective stores"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/build/**/*
          generate_release_notes: true

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Notify Discord
        run: echo "Send notification to Discord webhook"

      - name: Notify Slack
        run: echo "Send notification to Slack webhook"
