# Katya AI REChain Mesh - Indonesia Git System Configuration
# Platform Git Indonesia dan konfigurasi CI/CD

version: 1.0
name: "Katya AI REChain Mesh - Indonesia Systems"

# Platform Git Indonesia
platforms:
  - name: "GitHub Indonesia"
    region: "id"
    domain: "github.id"
    ci_cd: "github-actions"
    compliance: "PDP"
    language: "id"

  - name: "GitLab Indonesia"
    region: "id"
    domain: "gitlab.id"
    ci_cd: "gitlab-ci"
    compliance: "PDP"
    language: "id"

  - name: "Codeberg Indonesia"
    region: "id"
    domain: "codeberg.id"
    ci_cd: "woodpecker"
    compliance: "PDP"
    language: "id"

  - name: "Gitea Indonesia"
    region: "id"
    domain: "gitea.id"
    ci_cd: "gitea-actions"
    compliance: "PDP"
    language: "id"

# Penyedia cloud Indonesia
cloud_providers:
  - name: "AWS Indonesia (ap-southeast-3)"
    region: "jakarta"
    compliance: "PDP"
    data_residency: "indonesia"

  - name: "Azure Indonesia"
    region: "indonesiacentral"
    compliance: "PDP"
    data_residency: "indonesia"

  - name: "Google Cloud Indonesia"
    region: "asia-southeast2"
    compliance: "PDP"
    data_residency: "indonesia"

  - name: "Alibaba Cloud Indonesia"
    region: "indonesia"
    compliance: "PDP"
    data_residency: "indonesia"

  - name: "Telkom Indonesia Cloud"
    region: "indonesia"
    compliance: "PDP"
    data_residency: "indonesia"

  - name: "Indosat Cloud"
    region: "indonesia"
    compliance: "PDP"
    data_residency: "indonesia"

  - name: "XL Axiata Cloud"
    region: "indonesia"
    compliance: "PDP"
    data_residency: "indonesia"

# Kepatuhan dan standar
compliance:
  pdp: true
  iso27001: true
  bank_indonesia: true
  ojk: true

# Lokalisasi Indonesia
localization:
  primary: "id-ID"
  secondary: ["en-ID", "jv-ID", "su-ID", "ms-ID", "zh-ID", "ar-ID", "hi-ID"]
  currency: "IDR"
  timezone: "Asia/Jakarta"

# Pipeline CI/CD untuk platform Indonesia
github_actions_indonesia: |
  name: Indonesia CI/CD
  on: [push, pull_request]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.0'
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test
        - run: flutter build apk --release
        - run: flutter build ios --release --no-codesign
        - run: flutter build web --release

# Toko Indonesia
deployment:
  google_play_indonesia:
    track: "alpha"
    language: "id"
    countries: ["ID"]

  app_store_indonesia:
    region: "id"
    language: "id"
    countries: ["ID"]

  huawei_appgallery_indonesia:
    region: "id"
    language: "id"

  galaxy_store_indonesia:
    region: "id"
    language: "id"

# Sistem pembayaran Indonesia
payment_systems:
  - name: "GoPay"
    type: "digital_wallet"
    region: "id"

  - name: "OVO"
    type: "digital_wallet"
    region: "id"

  - name: "DANA"
    type: "digital_wallet"
    region: "id"

  - name: "LinkAja"
    type: "digital_wallet"
    region: "id"

  - name: "ShopeePay"
    type: "digital_wallet"
    region: "id"

  - name: "BCA Mobile"
    type: "mobile_banking"
    region: "id"

  - name: "Mandiri Online"
    type: "mobile_banking"
    region: "id"

  - name: "BNI Mobile"
    type: "mobile_banking"
    region: "id"

  - name: "BRI Mobile"
    type: "mobile_banking"
    region: "id"

  - name: "CIMB Niaga"
    type: "mobile_banking"
    region: "id"

# Integrasi sosial Indonesia
social_integration:
  - name: "WhatsApp Indonesia"
    type: "messaging"
    region: "id"

  - name: "Facebook Indonesia"
    type: "social"
    region: "id"

  - name: "Instagram Indonesia"
    type: "social"
    region: "id"

  - name: "Twitter Indonesia"
    type: "social"
    region: "id"

  - name: "YouTube Indonesia"
    type: "video"
    region: "id"

  - name: "TikTok Indonesia"
    type: "video"
    region: "id"

  - name: "LINE Indonesia"
    type: "messaging"
    region: "id"

# Bahasa Indonesia
languages:
  indonesian: "Bahasa Indonesia"
  english: "English"
  javanese: "Basa Jawa"
  sundanese: "Basa Sunda"
  malay: "Bahasa Melayu"
  chinese: "中文"
  arabic: "العربية"
  hindi: "हिन्दी"

# Provinsi Indonesia
provinces:
  - "Aceh"
  - "Sumatera Utara"
  - "Sumatera Barat"
  - "Riau"
  - "Jambi"
  - "Sumatera Selatan"
  - "Bengkulu"
  - "Lampung"
  - "Kepulauan Bangka Belitung"
  - "Kepulauan Riau"
  - "DKI Jakarta"
  - "Jawa Barat"
  - "Jawa Tengah"
  - "DI Yogyakarta"
  - "Jawa Timur"
  - "Banten"
  - "Bali"
  - "Nusa Tenggara Barat"
  - "Nusa Tenggara Timur"
  - "Kalimantan Barat"
  - "Kalimantan Tengah"
  - "Kalimantan Selatan"
  - "Kalimantan Timur"
  - "Kalimantan Utara"
  - "Sulawesi Utara"
  - "Sulawesi Tengah"
  - "Sulawesi Selatan"
  - "Sulawesi Tenggara"
  - "Gorontalo"
  - "Sulawesi Barat"
  - "Maluku"
  - "Maluku Utara"
  - "Papua Barat"
  - "Papua"
