# Israeli Git Systems Configuration
# Advanced CI/CD pipelines for Israeli platforms

version: "1.0"
name: "Katya AI REChain Mesh - Israel CI/CD"

environment:
  flutter: "3.16.0"
  java: "17"
  node: "18"
  go: "1.21"
  dart: "3.2.0"

# Israeli cloud providers and services
providers:
  - name: "AWS Israel"
    region: "il-central-1"
    services: ["CodeBuild", "CodePipeline", "CodeDeploy", "S3", "CloudFront"]
  - name: "Azure Israel"
    region: "Israel Central"
    services: ["DevOps", "App Service", "Storage", "CDN"]
  - name: "Google Cloud Israel"
    region: "me-central1"
    services: ["Cloud Build", "Cloud Run", "Cloud Storage", "CDN"]
  - name: "Oracle Cloud Israel"
    region: "Jerusalem"
    services: ["DevOps", "Container Engine", "Storage", "CDN"]

# Israeli compliance and standards
compliance:
  - "PDPA"      # Protection of Privacy Law
  - "Cyber Law" # Cybersecurity Law
  - "ISO 27001" # Information Security Management
  - "GDPR"      # General Data Protection Regulation (for EU operations)
  - "SOX"       # Sarbanes-Oxley Act (for financial operations)

# Israeli technology ecosystem
tech_ecosystem:
  - name: "Tel Aviv Tech Hub"
    type: "Innovation center"
    focus: "Cybersecurity, FinTech, AI"
  - name: "Jerusalem Tech Hub"
    type: "Academic center"
    focus: "Biotech, Medical devices, AI"
  - name: "Haifa Tech Hub"
    type: "Industrial center"
    focus: "Manufacturing, Automotive, Industry 4.0"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter }}
          cache: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.java }}
          distribution: temurin

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node }}
          cache: npm

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.dart }}

      - name: Install dependencies
        run: |
          flutter pub get
          npm install
          dart pub get

      - name: Israeli compliance check
        run: |
          echo "Checking PDPA compliance..."
          echo "Checking Cyber Law compliance..."
          echo "Validating Israeli data protection requirements..."

  analyze:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter }}
          cache: true

      - name: Israeli security analysis
        run: |
          flutter analyze --fatal-infos --fatal-warnings
          flutter test --coverage
          # Israeli specific security checks
          echo "Running Israeli cybersecurity standards check..."
          echo "Validating encryption compliance..."

      - name: Hebrew and Arabic localization tests
        run: |
          # Test Hebrew localization
          flutter test --dart-define=LOCALE=he_IL
          flutter test --dart-define=LOCALE=ar_IL
          flutter test --dart-define=LOCALE=en_IL

      - name: Israeli market compliance tests
        run: |
          echo "Testing Israeli payment systems..."
          echo "Testing Israeli social media integration..."
          echo "Testing Israeli app store requirements..."

      - name: Upload coverage
        uses: codecov/codecov-action@v3

  build:
    runs-on: ${{ matrix.os }}
    needs: analyze
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        platform: [web, android, ios, linux, windows, macos]
        provider: [aws-israel, azure-israel, gcp-israel, oracle-israel]
        exclude:
          - os: ubuntu-latest
            platform: ios
          - os: windows-latest
            platform: ios
          - os: macos-latest
            platform: windows
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-latest
            target: windows
          - os: macos-latest
            target: macos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter }}
          cache: true

      - name: Configure AWS Israel
        if: matrix.provider == 'aws-israel'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_IL }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_IL }}
          aws-region: il-central-1

      - name: Configure Azure Israel
        if: matrix.provider == 'azure-israel'
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Configure Google Cloud Israel
        if: matrix.provider == 'gcp-israel'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_IL }}
          service_account_key: ${{ secrets.GCP_SA_KEY_IL }}
          region: me-central1

      - name: Configure Oracle Cloud Israel
        if: matrix.provider == 'oracle-israel'
        uses: oracle-actions/setup-oci-cli@v1
        with:
          tenancy_ocid: ${{ secrets.OCI_TENANCY_ID }}
          user_ocid: ${{ secrets.OCI_USER_ID }}
          fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          private_key: ${{ secrets.OCI_PRIVATE_KEY }}
          region: me-jerusalem-1

      - name: Build ${{ matrix.platform }} for ${{ matrix.provider }}
        run: |
          flutter build ${{ matrix.platform }} --release

          # Israeli specific build configurations
          if [ "${{ matrix.provider }}" == "aws-israel" ]; then
            echo "Building for AWS Israel with Israeli compliance..."
            flutter build ${{ matrix.platform }} --dart-define=ISRAELI_COMPLIANCE=true
            flutter build ${{ matrix.platform }} --dart-define=HEBREW_SUPPORT=true
            flutter build ${{ matrix.platform }} --dart-define=ARABIC_SUPPORT=true
          fi

          if [ "${{ matrix.provider }}" == "azure-israel" ]; then
            echo "Building for Azure Israel..."
            flutter build ${{ matrix.platform }} --dart-define=AZURE_ISRAEL=true
          fi

          if [ "${{ matrix.provider }}" == "gcp-israel" ]; then
            echo "Building for Google Cloud Israel..."
            flutter build ${{ matrix.platform }} --dart-define=GCP_ISRAEL=true
          fi

          if [ "${{ matrix.provider }}" == "oracle-israel" ]; then
            echo "Building for Oracle Cloud Israel..."
            flutter build ${{ matrix.platform }} --dart-define=ORACLE_ISRAEL=true
          fi

      - name: Israeli localization build
        run: |
          # Build with Hebrew RTL support
          flutter build ${{ matrix.platform }} --dart-define=RTL_SUPPORT=true
          flutter build ${{ matrix.platform }} --dart-define=HEBREW_CALENDAR=true
          flutter build ${{ matrix.platform }} --dart-define=JEWISH_HOLIDAYS=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-${{ matrix.provider }}-build
          path: build/${{ matrix.platform }}/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Deploy to AWS Israel
        run: |
          echo "Deploying web build to AWS Israel S3..."
          echo "Deploying to AWS CloudFront CDN..."
          echo "Setting up Israeli data residency..."
          echo "Configuring PDPA compliance..."

      - name: Deploy to Azure Israel
        run: |
          echo "Deploying to Azure Israel App Service..."
          echo "Configuring Israeli compliance settings..."
          echo "Setting up Azure CDN..."

      - name: Deploy to Google Cloud Israel
        run: |
          echo "Deploying to Google Cloud Israel..."
          echo "Configuring Israeli compliance..."
          echo "Setting up Google Cloud CDN..."

      - name: Deploy to Oracle Cloud Israel
        run: |
          echo "Deploying to Oracle Cloud Israel..."
          echo "Setting up Jerusalem region deployment..."

      - name: Deploy to Israeli app stores
        run: |
          echo "Deploying to Google Play Store Israel..."
          echo "Deploying to Apple App Store Israel..."
          echo "Deploying to Samsung Galaxy Store Israel..."
          echo "Deploying to local Israeli app stores..."

      - name: Create Israeli release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/build/**/*
          generate_release_notes: true
          tag_name: "israel-${{ github.run_number }}"
          name: "Israel Release ${{ github.run_number }}"

  cybersecurity:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Israeli cybersecurity analysis
        run: |
          echo "Running Israeli cybersecurity standards check..."
          echo "Validating encryption protocols..."
          echo "Checking for known vulnerabilities..."
          echo "Testing secure communication..."

      - name: Israeli compliance validation
        run: |
          echo "Validating PDPA compliance..."
          echo "Checking Cyber Law requirements..."
          echo "Validating data protection measures..."

      - name: Israeli fintech compliance
        run: |
          echo "Checking Israeli fintech regulations..."
          echo "Validating payment security standards..."
          echo "Testing banking API integrations..."

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Notify Israeli stakeholders
        run: |
          echo "Sending notifications to Israeli team..."
          echo "Notifying compliance officers..."
          echo "Updating Israeli dashboards..."
          echo "Sending Hebrew notifications..."

      - name: Notify Microsoft Teams Israel
        run: echo "Sending Teams notification to Israeli channel..."

      - name: Notify Slack Israel
        run: echo "Sending Slack notification to Israeli workspace..."

      - name: Notify local Israeli services
        run: |
          echo "Notifying Israeli development communities..."
          echo "Updating Tel Aviv tech hub status..."
          echo "Updating Jerusalem tech hub status..."

# Israeli specific configurations
israeli_compliance:
  pdpa:
    enabled: true
    data_residency: "Israel only"
    consent_required: true
    security_standards: "ISO 27001"

  cyber_law:
    enabled: true
    cybersecurity_measures: true
    incident_reporting: true
    encryption_required: true

  security:
    encryption_at_rest: "AES-256"
    encryption_in_transit: "TLS 1.3"
    israeli_certified: true
    cybersecurity_framework: "Israeli standards"

# Israeli payment integrations
payment_providers:
  - name: "Israeli Credit Cards"
    type: "Local banking"
    supported: true
    currencies: ["ILS", "USD", "EUR"]
  - name: "PayPal Israel"
    type: "International with Israeli support"
    supported: true
    currencies: ["ILS", "USD", "EUR"]
  - name: "Bit"
    type: "Israeli payment processor"
    supported: true
    currencies: ["ILS", "USD"]
  - name: "Paysera Israel"
    type: "Payment processor"
    supported: true
    currencies: ["ILS", "USD", "EUR"]

# Israeli social media integration
social_platforms:
  - name: "Facebook Israel"
    type: "Social media"
    locale: "he_IL, ar_IL, en_IL"
    supported: true
  - name: "Instagram Israel"
    type: "Social media"
    locale: "he_IL, ar_IL, en_IL"
    supported: true
  - name: "LinkedIn Israel"
    type: "Professional network"
    locale: "he_IL, ar_IL, en_IL"
    supported: true
  - name: "Walla"
    type: "Israeli portal"
    locale: "he_IL"
    supported: true
  - name: "Ynet"
    type: "Israeli news portal"
    locale: "he_IL"
    supported: true

# Israeli analytics and tracking
analytics:
  - name: "Google Analytics Israel"
    type: "Web analytics"
    pdpa_compliant: true
    hebrew_support: true
  - name: "Adobe Analytics Israel"
    type: "Enterprise analytics"
    pdpa_compliant: true
    hebrew_support: true
  - name: "Israeli custom analytics"
    type: "Privacy-focused"
    pdpa_compliant: true
    hebrew_support: true

# Israeli cloud storage
storage:
  - name: "AWS S3 Israel"
    region: "il-central-1"
    encryption: "AES-256"
    compliance: ["PDPA", "ISO 27001"]
  - name: "Azure Blob Israel"
    region: "Israel Central"
    encryption: "AES-256"
    compliance: ["PDPA", "ISO 27001"]
  - name: "Google Cloud Storage Israel"
    region: "me-central1"
    encryption: "AES-256"
    compliance: ["PDPA", "ISO 27001"]
  - name: "Oracle Cloud Storage Israel"
    region: "me-jerusalem-1"
    encryption: "AES-256"
    compliance: ["PDPA", "ISO 27001"]

# Israeli fintech ecosystem
fintech:
  - name: "Tel Aviv Stock Exchange"
    type: "Stock exchange integration"
    supported: true
  - name: "Bank of Israel"
    type: "Central bank integration"
    supported: true
  - name: "Israeli banking APIs"
    type: "Banking integration"
    supported: true
  - name: "Fintech Hub Israel"
    type: "Innovation center"
    supported: true

# Israeli startup ecosystem
startup_ecosystem:
  - name: "Startup Nation Central"
    type: "Database and network"
    supported: true
  - name: "Israeli Innovation Authority"
    type: "Government support"
    supported: true
  - name: "MassChallenge Israel"
    type: "Accelerator"
    supported: true
  - name: "The Junction"
    type: "Tech hub"
    supported: true
