# Katya AI REChain Mesh - Japan Git System Configuration
# 日本のGitプラットフォームとCI/CD設定

version: 1.0
name: "Katya AI REChain Mesh - Japan Systems"

# 日本のGitプラットフォーム
platforms:
  - name: "GitHub Japan"
    region: "jp"
    domain: "github.co.jp"
    ci_cd: "github-actions"
    compliance: "APPI"
    language: "ja"

  - name: "GitLab Japan"
    region: "jp"
    domain: "gitlab.co.jp"
    ci_cd: "gitlab-ci"
    compliance: "APPI"
    language: "ja"

  - name: "Codeberg Japan"
    region: "jp"
    domain: "codeberg.jp"
    ci_cd: "woodpecker"
    compliance: "APPI"
    language: "ja"

  - name: "Gitea Japan"
    region: "jp"
    domain: "gitea.jp"
    ci_cd: "gitea-actions"
    compliance: "APPI"
    language: "ja"

# 日本のクラウドプロバイダー
cloud_providers:
  - name: "AWS Japan (ap-northeast-1)"
    region: "tokyo"
    compliance: "APPI"
    data_residency: "japan"

  - name: "Azure Japan"
    region: "japanwest"
    compliance: "APPI"
    data_residency: "japan"

  - name: "Google Cloud Japan"
    region: "asia-northeast1"
    compliance: "APPI"
    data_residency: "japan"

  - name: "NTT Cloud"
    region: "japan"
    compliance: "APPI"
    data_residency: "japan"

  - name: "Fujitsu Cloud"
    region: "japan"
    compliance: "APPI"
    data_residency: "japan"

  - name: "NEC Cloud"
    region: "japan"
    compliance: "APPI"
    data_residency: "japan"

# コンプライアンスと規格
compliance:
  appi: true
  iso27001: true
  fisc: true
  mitre_att&ck: true

# 日本のローカライズ
localization:
  primary: "ja-JP"
  currency: "JPY"
  timezone: "Asia/Tokyo"
  encoding: "UTF-8"

# CI/CDパイプライン（日本語プラットフォーム用）
github_actions_japan: |
  name: 日本のCI/CD
  on: [push, pull_request]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Flutterセットアップ
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.0'
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test
        - run: flutter build apk --release
        - run: flutter build ios --release --no-codesign
        - run: flutter build web --release

gitlab_ci_japan: |
  stages:
    - ビルド
    - テスト
    - デプロイ

  variables:
    FLUTTER_VERSION: "3.16.0"

  build:android:
    stage: ビルド
    script:
      - flutter pub get
      - flutter analyze --fatal-infos --fatal-warnings
      - flutter test --coverage
      - flutter build apk --release
    artifacts:
      paths:
        - build/app/outputs/
    coverage: '/Coverage: \d+\.\d+%/'

  build:ios:
    stage: ビルド
    script:
      - flutter build ios --release --no-codesign
    artifacts:
      paths:
        - build/ios/

  build:web:
    stage: ビルド
    script:
      - flutter build web --release
    artifacts:
      paths:
        - build/web/

# 日本のストアデプロイ
deployment:
  google_play_japan:
    track: "alpha"
    language: "ja"
    countries: ["JP"]

  app_store_japan:
    region: "jp"
    language: "ja"
    countries: ["JP"]

  huawei_appgallery_japan:
    region: "jp"
    language: "ja"

  galaxy_store_japan:
    region: "jp"
    language: "ja"

# 日本語支払いシステム
payment_systems:
  - name: "PayPay"
    type: "mobile_payment"
    region: "jp"

  - name: "LINE Pay"
    type: "mobile_payment"
    region: "jp"

  - name: "楽天ペイ"
    type: "mobile_payment"
    region: "jp"

  - name: "メルペイ"
    type: "mobile_payment"
    region: "jp"

  - name: "d払い"
    type: "mobile_payment"
    region: "jp"

  - name: "au PAY"
    type: "mobile_payment"
    region: "jp"

# 日本のSNS連携
social_integration:
  - name: "LINE"
    type: "messaging"
    region: "jp"

  - name: "Twitter Japan"
    type: "social"
    region: "jp"

  - name: "Instagram Japan"
    type: "social"
    region: "jp"

  - name: "YouTube Japan"
    type: "video"
    region: "jp"
