# Katya AI REChain Mesh - Netherlands Git System Configuration
# Nederlandse Git-platformen en CI/CD configuratie

version: 1.0
name: "Katya AI REChain Mesh - Netherlands Systems"

# Nederlandse Git-platformen
platforms:
  - name: "GitHub Netherlands"
    region: "nl"
    domain: "github.nl"
    ci_cd: "github-actions"
    compliance: "AVG"
    language: "nl"

  - name: "GitLab Netherlands"
    region: "nl"
    domain: "gitlab.nl"
    ci_cd: "gitlab-ci"
    compliance: "AVG"
    language: "nl"

  - name: "Codeberg Netherlands"
    region: "nl"
    domain: "codeberg.nl"
    ci_cd: "woodpecker"
    compliance: "AVG"
    language: "nl"

# Nederlandse cloud-aanbieders
cloud_providers:
  - name: "AWS Netherlands (eu-west-1)"
    region: "ireland"
    compliance: "AVG"
    data_residency: "europe"

  - name: "Azure Netherlands"
    region: "westeurope"
    compliance: "AVG"
    data_residency: "europe"

  - name: "Google Cloud Netherlands"
    region: "europe-west4"
    compliance: "AVG"
    data_residency: "europe"

# Compliance en standaarden
compliance:
  avg: true
  iso27001: true
  nen7510: true
  bir: true

# Nederlandse lokalisatie
localization:
  primary: "nl-NL"
  secondary: ["nl-BE", "en-NL", "fy-NL"]
  currency: "EUR"
  timezone: "Europe/Amsterdam"

# CI/CD pipelines voor Nederlandse platformen
github_actions_netherlands: |
  name: Nederlandse CI/CD
  on: [push, pull_request]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Flutter instellen
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.0'
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test
        - run: flutter build apk --release
        - run: flutter build ios --release --no-codesign
        - run: flutter build web --release

# Nederlandse stores
deployment:
  google_play_netherlands:
    track: "alpha"
    language: "nl"
    countries: ["NL"]

  app_store_netherlands:
    region: "nl"
    language: "nl"
    countries: ["NL"]

# Nederlandse betaalsystemen
payment_systems:
  - name: "iDEAL"
    type: "online_banking"
    region: "nl"

  - name: "Bancontact"
    type: "mobile_payment"
    region: "nl"

  - name: "PayPal Netherlands"
    type: "digital_wallet"
    region: "nl"

# Nederlandse sociale integratie
social_integration:
  - name: "WhatsApp Netherlands"
    type: "messaging"
    region: "nl"

  - name: "Facebook Netherlands"
    type: "social"
    region: "nl"

  - name: "LinkedIn Netherlands"
    type: "professional"
    region: "nl"
