# Katya AI REChain Mesh - Russia Extended Git System Configuration
# Расширенная конфигурация Git для России и стран СНГ

version: 2.0
name: "Katya AI REChain Mesh - Russia Extended Systems"

# Российские Git-платформы (дополнительно к существующим)
platforms:
  - name: "GitHub Russia"
    region: "ru"
    domain: "github.ru"
    ci_cd: "github-actions"
    compliance: "152-FZ"
    language: "ru"

  - name: "GitLab Russia"
    region: "ru"
    domain: "gitlab.ru"
    ci_cd: "gitlab-ci"
    compliance: "152-FZ"
    language: "ru"

  - name: "Gitea Russia"
    region: "ru"
    domain: "gitea.ru"
    ci_cd: "gitea-actions"
    compliance: "152-FZ"
    language: "ru"

  - name: "Radicle Russia"
    region: "ru"
    domain: "radicle.ru"
    ci_cd: "radicle"
    compliance: "152-FZ"
    language: "ru"

  - name: "Forgejo Russia"
    region: "ru"
    domain: "forgejo.ru"
    ci_cd: "forgejo-actions"
    compliance: "152-FZ"
    language: "ru"

# Российские облачные провайдеры
cloud_providers:
  - name: "Yandex Cloud"
    region: "ru-central1"
    compliance: "152-FZ"
    data_residency: "russia"

  - name: "SberCloud"
    region: "ru-central1"
    compliance: "152-FZ"
    data_residency: "russia"

  - name: "VK Cloud"
    region: "ru-central1"
    compliance: "152-FZ"
    data_residency: "russia"

  - name: "MTS Cloud"
    region: "ru-central1"
    compliance: "152-FZ"
    data_residency: "russia"

  - name: "Rostelecom Cloud"
    region: "ru-central1"
    compliance: "152-FZ"
    data_residency: "russia"

  - name: "Selectel"
    region: "ru-central1"
    compliance: "152-FZ"
    data_residency: "russia"

# Регуляторные требования
compliance:
  "152_fz": true
  "187_fz": true
  "149_fz": true
  iso27001: true
  gost_r: true
  fstek: true

# Русская локализация (расширенная)
localization:
  primary: "ru-RU"
  secondary: ["ru-BY", "ru-KZ", "ru-UA", "ru-UZ", "ru-KG", "ru-TJ", "ru-TM", "ru-AZ", "ru-AM", "ru-GE"]
  currency: "RUB"
  timezone: "Europe/Moscow"

# CI/CD пайплайны для русских платформ
github_actions_russia: |
  name: Российский CI/CD
  on: [push, pull_request]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Настройка Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.0'
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test
        - run: flutter build apk --release
        - run: flutter build ios --release --no-codesign
        - run: flutter build web --release

gitlab_ci_russia: |
  stages:
    - сборка
    - тестирование
    - развертывание

  variables:
    FLUTTER_VERSION: "3.16.0"

  build:android:
    stage: сборка
    script:
      - flutter pub get
      - flutter analyze --fatal-infos --fatal-warnings
      - flutter test --coverage
      - flutter build apk --release
    artifacts:
      paths:
        - build/app/outputs/
    coverage: '/Coverage: \d+\.\d+%/'

  build:ios:
    stage: сборка
    script:
      - flutter build ios --release --no-codesign
    artifacts:
      paths:
        - build/ios/

  build:web:
    stage: сборка
    script:
      - flutter build web --release
    artifacts:
      paths:
        - build/web/

# Развертывание для русских магазинов
deployment:
  google_play_russia:
    track: "alpha"
    language: "ru"
    countries: ["RU"]

  app_store_russia:
    region: "ru"
    language: "ru"
    countries: ["RU"]

  huawei_appgallery_russia:
    region: "ru"
    language: "ru"

  galaxy_store_russia:
    region: "ru"
    language: "ru"

  nashstore:
    region: "ru"
    language: "ru"

  rustore:
    region: "ru"
    language: "ru"

  apkpure_russia:
    region: "ru"
    language: "ru"

# Российские платежные системы
payment_systems:
  - name: "СБП (Система быстрых платежей)"
    type: "instant_payment"
    region: "ru"

  - name: "Сбербанк Онлайн"
    type: "banking_app"
    region: "ru"

  - name: "Тинькофф"
    type: "digital_bank"
    region: "ru"

  - name: "Альфа-Банк"
    type: "banking_app"
    region: "ru"

  - name: "ВТБ"
    type: "banking_app"
    region: "ru"

  - name: "Газпромбанк"
    type: "banking_app"
    region: "ru"

  - name: "Райффайзенбанк"
    type: "banking_app"
    region: "ru"

  - name: "ЮMoney"
    type: "digital_wallet"
    region: "ru"

  - name: "QIWI Кошелек"
    type: "digital_wallet"
    region: "ru"

  - name: "WebMoney"
    type: "digital_wallet"
    region: "ru"

# Российские социальные сети
social_integration:
  - name: "ВКонтакте"
    type: "social_network"
    region: "ru"

  - name: "Одноклассники"
    type: "social_network"
    region: "ru"

  - name: "Telegram"
    type: "messaging"
    region: "ru"

  - name: "Дзен"
    type: "content_platform"
    region: "ru"

  - name: "Рутуб"
    type: "video_platform"
    region: "ru"

  - name: "Discord (русскоязычные серверы)"
    type: "messaging"
    region: "ru"

# Страны СНГ
cis_countries:
  - "RU"  # Россия
  - "BY"  # Беларусь
  - "KZ"  # Казахстан
  - "UA"  # Украина
  - "UZ"  # Узбекистан
  - "KG"  # Кыргызстан
  - "TJ"  # Таджикистан
  - "TM"  # Туркменистан
  - "AZ"  # Азербайджан
  - "AM"  # Армения
  - "GE"  # Грузия
  - "MD"  # Молдова

# Языки СНГ
languages:
  russian: "Русский"
  belarusian: "Беларуская"
  kazakh: "Қазақша"
  ukrainian: "Українська"
  uzbek: "O'zbekcha"
  kyrgyz: "Кыргызча"
  tajik: "Тоҷикӣ"
  turkmen: "Türkmençe"
  azerbaijani: "Azərbaycan dili"
  armenian: "Հայերեն"
  georgian: "ქართული"
  moldovan: "Moldovenească"

# Российские стандарты шифрования
encryption_standards:
  gost_28147_89: true
  gost_r_34_12_2015: true
  gost_r_34_10_2012: true

# Российские центры обработки данных
data_centers:
  - name: "Москва (M9)"
    region: "ru-central1-a"
    provider: "yandex"

  - name: "Санкт-Петербург (SPB1)"
    region: "ru-central1-b"
    provider: "yandex"

  - name: "Екатеринбург"
    region: "ru-central1-c"
    provider: "selectel"

  - name: "Новосибирск"
    region: "ru-central1-d"
    provider: "selectel"
