# Katya AI REChain Mesh - South Africa Git System Configuration
# South African Git platforms and CI/CD configuration

version: 1.0
name: "Katya AI REChain Mesh - South Africa Systems"

# South African Git platforms
platforms:
  - name: "GitHub South Africa"
    region: "za"
    domain: "github.co.za"
    ci_cd: "github-actions"
    compliance: "POPIA"
    language: "en-ZA"

  - name: "GitLab South Africa"
    region: "za"
    domain: "gitlab.co.za"
    ci_cd: "gitlab-ci"
    compliance: "POPIA"
    language: "en-ZA"

  - name: "Codeberg South Africa"
    region: "za"
    domain: "codeberg.za"
    ci_cd: "woodpecker"
    compliance: "POPIA"
    language: "en-ZA"

  - name: "Gitea South Africa"
    region: "za"
    domain: "gitea.za"
    ci_cd: "gitea-actions"
    compliance: "POPIA"
    language: "en-ZA"

# South African cloud providers
cloud_providers:
  - name: "AWS South Africa (af-south-1)"
    region: "cape_town"
    compliance: "POPIA"
    data_residency: "south_africa"

  - name: "Azure South Africa"
    region: "southafricanorth"
    compliance: "POPIA"
    data_residency: "south_africa"

  - name: "Google Cloud South Africa"
    region: "africa-south1"
    compliance: "POPIA"
    data_residency: "south_africa"

  - name: "Teraco"
    region: "south_africa"
    compliance: "POPIA"
    data_residency: "south_africa"

  - name: "Napafrica"
    region: "south_africa"
    compliance: "POPIA"
    data_residency: "south_africa"

  - name: "Vodacom Cloud"
    region: "south_africa"
    compliance: "POPIA"
    data_residency: "south_africa"

  - name: "MTN Business Cloud"
    region: "south_africa"
    compliance: "POPIA"
    data_residency: "south_africa"

# Compliance and standards
compliance:
  popia: true
  iso27001: true
  king_iv: true
  ndp: true

# South African localization
localization:
  primary: "en-ZA"
  secondary: ["af-ZA", "zu-ZA", "xh-ZA", "st-ZA", "tn-ZA", "ts-ZA", "ve-ZA", "nr-ZA", "ss-ZA"]
  currency: "ZAR"
  timezone: "Africa/Johannesburg"

# CI/CD pipelines for South African platforms
github_actions_south_africa: |
  name: South Africa CI/CD
  on: [push, pull_request]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.0'
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test
        - run: flutter build apk --release
        - run: flutter build ios --release --no-codesign
        - run: flutter build web --release

gitlab_ci_south_africa: |
  stages:
    - build
    - test
    - deploy

  variables:
    FLUTTER_VERSION: "3.16.0"

  build:android:
    stage: build
    script:
      - flutter pub get
      - flutter analyze --fatal-infos --fatal-warnings
      - flutter test --coverage
      - flutter build apk --release
    artifacts:
      paths:
        - build/app/outputs/
    coverage: '/Coverage: \d+\.\d+%/'

  build:ios:
    stage: build
    script:
      - flutter build ios --release --no-codesign
    artifacts:
      paths:
        - build/ios/

  build:web:
    stage: build
    script:
      - flutter build web --release
    artifacts:
      paths:
        - build/web/

# Deployment for South African stores
deployment:
  google_play_south_africa:
    track: "alpha"
    language: "en-ZA"
    countries: ["ZA"]

  app_store_south_africa:
    region: "za"
    language: "en-ZA"
    countries: ["ZA"]

  huawei_appgallery_south_africa:
    region: "za"
    language: "en-ZA"

  galaxy_store_south_africa:
    region: "za"
    language: "en-ZA"

# South African payment systems
payment_systems:
  - name: "SnapScan"
    type: "mobile_payment"
    region: "za"

  - name: "Zapper"
    type: "mobile_payment"
    region: "za"

  - name: "Masterpass"
    type: "digital_wallet"
    region: "za"

  - name: "FNB Pay"
    type: "banking_payment"
    region: "za"

  - name: "Nedbank Pay"
    type: "banking_payment"
    region: "za"

  - name: "Standard Bank Pay"
    type: "banking_payment"
    region: "za"

  - name: "Capitec Pay"
    type: "banking_payment"
    region: "za"

  - name: "Absa Pay"
    type: "banking_payment"
    region: "za"

  - name: "TymeBank"
    type: "digital_bank"
    region: "za"

  - name: "Discovery Bank"
    type: "digital_bank"
    region: "za"

# South African social integration
social_integration:
  - name: "WhatsApp South Africa"
    type: "messaging"
    region: "za"

  - name: "Facebook South Africa"
    type: "social"
    region: "za"

  - name: "Twitter South Africa"
    type: "social"
    region: "za"

  - name: "Instagram South Africa"
    type: "social"
    region: "za"

  - name: "LinkedIn South Africa"
    type: "professional"
    region: "za"

  - name: "YouTube South Africa"
    type: "video"
    region: "za"

# South African languages
languages:
  english: "English"
  afrikaans: "Afrikaans"
  zulu: "isiZulu"
  xhosa: "isiXhosa"
  sotho: "Sesotho"
  tswana: "Setswana"
  tsonga: "Xitsonga"
  venda: "Tshivenda"
  ndebele: "isiNdebele"
  swati: "siSwati"
  pedi: "Sepedi"

# African Union countries
african_union_countries:
  - "ZA"  # South Africa
  - "EG"  # Egypt
  - "NG"  # Nigeria
  - "KE"  # Kenya
  - "GH"  # Ghana
  - "ET"  # Ethiopia
  - "TZ"  # Tanzania
  - "UG"  # Uganda
  - "MA"  # Morocco
  - "DZ"  # Algeria
  - "TN"  # Tunisia
  - "BW"  # Botswana
  - "ZW"  # Zimbabwe
  - "MZ"  # Mozambique
  - "AO"  # Angola
  - "ZM"  # Zambia
  - "MW"  # Malawi
  - "NA"  # Namibia
  - "BJ"  # Benin
  - "BF"  # Burkina Faso
  - "CV"  # Cape Verde
  - "TD"  # Chad
  - "KM"  # Comoros
  - "DJ"  # Djibouti
  - "ER"  # Eritrea
  - "GA"  # Gabon
  - "GM"  # Gambia
  - "GN"  # Guinea
  - "GW"  # Guinea-Bissau
  - "LS"  # Lesotho
  - "LR"  # Liberia
  - "LY"  # Libya
  - "ML"  # Mali
  - "MR"  # Mauritania
  - "MU"  # Mauritius
  - "NE"  # Niger
  - "RW"  # Rwanda
  - "ST"  # São Tomé and Príncipe
  - "SN"  # Senegal
  - "SC"  # Seychelles
  - "SL"  # Sierra Leone
  - "SO"  # Somalia
  - "SS"  # South Sudan
  - "SD"  # Sudan
  - "SZ"  # Eswatini
  - "TG"  # Togo
  - "TT"  # Trinidad and Tobago
  - "CM"  # Cameroon
  - "CF"  # Central African Republic
  - "CG"  # Republic of the Congo
  - "CD"  # Democratic Republic of the Congo
  - "GQ"  # Equatorial Guinea
  - "BI"  # Burundi
  - "CI"  # Côte d'Ivoire
  - "TL"  # Timor-Leste
