# Katya AI REChain Mesh - Thailand Git System Configuration
# แพลตฟอร์ม Git ไทยและการกำหนดค่า CI/CD

version: 1.0
name: "Katya AI REChain Mesh - Thailand Systems"

# แพลตฟอร์ม Git ไทย
platforms:
  - name: "GitHub Thailand"
    region: "th"
    domain: "github.th"
    ci_cd: "github-actions"
    compliance: "PDPA"
    language: "th"

  - name: "GitLab Thailand"
    region: "th"
    domain: "gitlab.th"
    ci_cd: "gitlab-ci"
    compliance: "PDPA"
    language: "th"

  - name: "Codeberg Thailand"
    region: "th"
    domain: "codeberg.th"
    ci_cd: "woodpecker"
    compliance: "PDPA"
    language: "th"

  - name: "Gitea Thailand"
    region: "th"
    domain: "gitea.th"
    ci_cd: "gitea-actions"
    compliance: "PDPA"
    language: "th"

# ผู้ให้บริการคลาวด์ไทย
cloud_providers:
  - name: "AWS Thailand (ap-southeast-1)"
    region: "bangkok"
    compliance: "PDPA"
    data_residency: "thailand"

  - name: "Azure Thailand"
    region: "thailandcentral"
    compliance: "PDPA"
    data_residency: "thailand"

  - name: "Google Cloud Thailand"
    region: "asia-southeast1"
    compliance: "PDPA"
    data_residency: "thailand"

  - name: "Alibaba Cloud Thailand"
    region: "thailand"
    compliance: "PDPA"
    data_residency: "thailand"

  - name: "True IDC Cloud"
    region: "thailand"
    compliance: "PDPA"
    data_residency: "thailand"

  - name: "AIS Cloud"
    region: "thailand"
    compliance: "PDPA"
    data_residency: "thailand"

  - name: "DTAC Cloud"
    region: "thailand"
    compliance: "PDPA"
    data_residency: "thailand"

# การปฏิบัติตามและมาตรฐาน
compliance:
  pdpa: true
  iso27001: true
  bank_of_thailand: true
  etda: true

# การแปลเป็นภาษาไทย
localization:
  primary: "th-TH"
  secondary: ["en-TH", "zh-TH", "ms-TH", "km-TH", "lo-TH", "my-TH"]
  currency: "THB"
  timezone: "Asia/Bangkok"

# ท่อส่ง CI/CD สำหรับแพลตฟอร์มไทย
github_actions_thailand: |
  name: ไทย CI/CD
  on: [push, pull_request]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: ตั้งค่า Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.0'
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test
        - run: flutter build apk --release
        - run: flutter build ios --release --no-codesign
        - run: flutter build web --release

# ร้านค้าไทย
deployment:
  google_play_thailand:
    track: "alpha"
    language: "th"
    countries: ["TH"]

  app_store_thailand:
    region: "th"
    language: "th"
    countries: ["TH"]

  huawei_appgallery_thailand:
    region: "th"
    language: "th"

  galaxy_store_thailand:
    region: "th"
    language: "th"

# ระบบการชำระเงินไทย
payment_systems:
  - name: "PromptPay"
    type: "instant_payment"
    region: "th"

  - name: "TrueMoney"
    type: "digital_wallet"
    region: "th"

  - name: "AIS mPAY"
    type: "mobile_payment"
    region: "th"

  - name: "DTAC mPAY"
    type: "mobile_payment"
    region: "th"

  - name: "Krung Thai"
    type: "mobile_banking"
    region: "th"

  - name: "SCB Easy"
    type: "mobile_banking"
    region: "th"

  - name: "KTB Netbank"
    type: "mobile_banking"
    region: "th"

  - name: "Bangkok Bank"
    type: "mobile_banking"
    region: "th"

  - name: "Kasikorn Bank"
    type: "mobile_banking"
    region: "th"

  - name: "TMB Touch"
    type: "mobile_banking"
    region: "th"

# การรวมโซเชียลไทย
social_integration:
  - name: "LINE Thailand"
    type: "messaging"
    region: "th"

  - name: "Facebook Thailand"
    type: "social"
    region: "th"

  - name: "Instagram Thailand"
    type: "social"
    region: "th"

  - name: "Twitter Thailand"
    type: "social"
    region: "th"

  - name: "YouTube Thailand"
    type: "video"
    region: "th"

  - name: "TikTok Thailand"
    type: "video"
    region: "th"

  - name: "Pantip"
    type: "forum"
    region: "th"

  - name: "Sanook"
    type: "portal"
    region: "th"

# ภาษาไทย
languages:
  thai: "ไทย"
  english: "English"
  chinese: "中文"
  malay: "Bahasa Melayu"
  khmer: "ភាសាខ្មែរ"
  lao: "ພາສາລາວ"
  burmese: "မြန်မာဘာသာ"

# จังหวัดไทย
provinces:
  - "กรุงเทพมหานคร"
  - "สมุทรปราการ"
  - "นนทบุรี"
  - "ปทุมธานี"
  - "พระนครศรีอยุธยา"
  - "อ่างทอง"
  - "ลพบุรี"
  - "สิงห์บุรี"
  - "ชัยนาท"
  - "สระบุรี"
  - "ชลบุรี"
  - "ระยอง"
  - "จันทบุรี"
  - "ตราด"
  - "ฉะเชิงเทรา"
  - "ปราจีนบุรี"
  - "นครนายก"
  - "สระแก้ว"
  - "นครราชสีมา"
  - "บุรีรัมย์"
  - "สุรินทร์"
  - "ศรีสะเกษ"
  - "อุบลราชธานี"
  - "ยโสธร"
  - "ชัยภูมิ"
  - "อำนาจเจริญ"
  - "หนองบัวลำภู"
  - "ขอนแก่น"
  - "อุดรธานี"
  - "เลย"
  - "หนองคาย"
  - "มหาสารคาม"
  - "ร้อยเอ็ด"
  - "กาฬสินธุ์"
  - "สกลนคร"
  - "นครพนม"
  - "มุกดาหาร"
  - "เชียงใหม่"
  - "ลำพูน"
  - "ลำปาง"
  - "อุตรดิตถ์"
  - "แพร่"
  - "น่าน"
  - "พะเยา"
  - "เชียงราย"
  - "แม่ฮ่องสอน"
  - "นครสวรรค์"
  - "อุทัยธานี"
  - "กำแพงเพชร"
  - "ตาก"
  - "สุโขทัย"
  - "พิษณุโลก"
  - "พิจิตร"
  - "เพชรบูรณ์"
  - "ราชบุรี"
  - "กาญจนบุรี"
  - "สุพรรณบุรี"
  - "นครปฐม"
  - "สมุทรสาคร"
  - "สมุทรสงคราม"
  - "เพชรบุรี"
  - "ประจวบคีรีขันธ์"
  - "นครศรีธรรมราช"
  - "กระบี่"
  - "พังงา"
  - "ภูเก็ต"
  - "สุราษฎร์ธานี"
  - "ระนอง"
  - "ชุมพร"
  - "สงขลา"
  - "สตูล"
  - "ตรัง"
  - "พัทลุง"
  - "ปัตตานี"
  - "ยะลา"
  - "นราธิวาส"
  - "บึงกาฬ"

# ประเทศอาเซียน
asean_countries:
  - "TH"  # ไทย
  - "SG"  # สิงคโปร์
  - "MY"  # มาเลเซีย
  - "ID"  # อินโดนีเซีย
  - "PH"  # ฟิลิปปินส์
  - "VN"  # เวียดนาม
  - "MM"  # เมียนมาร์
  - "KH"  # กัมพูชา
  - "LA"  # ลาว
  - "BN"  # บรูไน
  - "TL"  # ติมอร์-เลสเต
