targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
